name: frontend_estuaire_achats
description: >-
  Estuaire Achats : la marketplace 100% camerounaise !
  Achetez et vendez facilement des produits locaux (high-tech, mode, beauté, électroménager...).
  Switch entre mode client et vendeur, promotions, chat intégré et livraison à Douala, Yaoundé et plus.

publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: ^3.10.8

dependencies:
  flutter:
    sdk: flutter
  dio: ^5.7.0
  pretty_dio_logger: ^1.4.0


  firebase_core: ^3.6.0
  firebase_messaging: ^15.1.0
  flutter_local_notifications: ^17.2.0


  shimmer: ^3.0.0                     # Squelettes de chargement (produits, listes)
  carousel_slider: ^5.0.0             # Slider photos produit / bannières promo
  badges: ^3.1.2                      # Badge sur icône panier (nb articles)
  intl: ^0.19.0                       # Formatage prix (XAF/FCFA), dates
  permission_handler: ^11.3.1

  url_launcher: ^6.3.0                # Ouvrir WhatsApp vendeur, site, appel
  connectivity_plus: ^6.0.0           # Détecter connexion internet (mode offline panier ?)

  cupertino_icons: ^1.0.8
  get: ^4.7.3
  get_storage: ^2.1.1

dev_dependencies:
  flutter_test:
    sdk: flutter
  rename_app: ^1.6.5
  flutter_lints: ^6.0.0

flutter:

  uses-material-design: true

  # To add assets to your application, add an assets section, like this:
  assets:
    - assets/images/
    - assets/images/logo.png
    - assets/images/onboarding1.png
    - assets/images/onboarding2.png
    - assets/images/onboarding3.png

  # An image asset can refer to one or more resolution-specific "variants", see
  # https://flutter.dev/to/resolution-aware-images

  # For details regarding adding assets from package dependencies, see
  # https://flutter.dev/to/asset-from-package

  # To add custom fonts to your application, add a fonts section here,
  # in this "flutter" section. Each entry in this list should have a
  # "family" key with the font family name, and a "fonts" key with a
  # list giving the asset and other descriptors for the font. For
  # example:
  # fonts:
  #   - family: Schyler
  #     fonts:
  #       - asset: fonts/Schyler-Regular.ttf
  #       - asset: fonts/Schyler-Italic.ttf
  #         style: italic
  #   - family: Trajan Pro
  #     fonts:
  #       - asset: fonts/TrajanPro.ttf
  #       - asset: fonts/TrajanPro_Bold.ttf
  #         weight: 700
  #
  # For details regarding fonts from package dependencies,
  # see https://flutter.dev/to/font-from-package
